README.md, lib/ndr_dev_support/integration_testing.rb, lib/ndr_dev_support/integration_testing/connection_sharing.rb
Connection sharing support is no longer included by default when requiring the integration test helpers – it appears to be the cause of non-deterministic test failures in some projects. Other projects use the functionality without issue, so it remains available in `ndr_dev_support`.
=> Connection handling

lib/tasks/ci/prometheus.rake, lib/tasks/ci/slack.rake
These requires were missing from two rake CI setup tasks.
=> # Fixed missing highline dependencies

.rubocop.yml
@joshpencheon worth holding off on merging this until I work out how to fix `Metrics/LineLength`, I couldn't get `Exclude` or `ExcludedMethods` to work and willl need to look into it further. Relates to #27.
=> Replaced blanket db folder rubocop exclusion with cop specific exemptions

lib/ndr_dev_support/capistrano/ndr_model.rb, lib/ndr_dev_support/capistrano/standalone_gems.rb
Fixes an issue whereby capistrano couldn't install out-of-gems in NDR-model deployments
=> # capistrano: use passwordless sudo when installing out-of-bundle gems

lib/minitest/rake_ci.rb, lib/minitest/rake_ci_plugin.rb, lib/tasks/ci/minitest.rake
The preferred way of loading plugins is to have them in a discoverable location, and then the first plugin that is called loads all.
Directly hooking into `Minitest.extensions` prevented other plugins from being discovered after `rake_ci` loaded.
=> Avoid race condition when introducing minutest plugins

lib/ndr_dev_support/daemon/ci_server.rb, lib/tasks/ci/minitest.rake
@timgentry,
I think I've done basically what we discussed:
* I've added in some general log messages, to give an idea of progress / point of failure
* I've added logging of exceptions, as well as some new exceptions where things should perhaps be "fatal" (e.g. git/bundle failure - less convinced about the latter..?)
* I _haven't_ gone near the `git checkout -- . && git clean -fd`, as I wasn't sure if the files the server itself generates end up in untracked locations
* I _haven't_ actually configured a separate logger in this PR; calls to `log` will still head to stdout.
=> # ci_server: improve logging and error handling

lib/ndr_dev_support/integration_testing.rb
Sets the save path to `tmp/screenshots` (in line with the Rails convention) and set the prune strategy to keep 20 screenshots.
=> # Setting the Capybara save path and prune strategy. Resolves #45

lib/ndr_dev_support/rubocop/executor.rb
If amended code has a syntax error (e.g. a missing `end`), the `ruby -c` syntax error is now raised, rather than a spurious RuboCop error message.
=> # rake rubocop:diff now gracefully reports ruby syntax errors

lib/tasks/rubocop.rake
Useful when adding the gem to existing projects with no/different coding standards. Ordered by highest offence count first.
=> Added a rake rubocop:summary task to list offence counts by cop

CHANGELOG.md, lib/ndr_dev_support/integration_testing.rb, lib/ndr_dev_support/integration_testing/drivers/chrome.rb, lib/ndr_dev_support/integration_testing/drivers/chrome_headless.rb, ndr_dev_support.gemspec
The `chromedriver-helper` library is no longer being maintained, and the de-facto path is to switch to `webdrivers`.
=> # switch to webdrivers from chromedriver-helper. Resolves #53

CHANGELOG.md, lib/ndr_dev_support/integration_testing/drivers/chrome.rb, lib/ndr_dev_support/integration_testing/drivers/chrome_headless.rb, lib/ndr_dev_support/integration_testing/drivers/firefox.rb, lib/ndr_dev_support/integration_testing/drivers/poltergeist.rb, lib/ndr_dev_support/integration_testing/drivers/switchable.rb, lib/ndr_dev_support/integration_testing/dsl.rb, ndr_dev_support.gemspec
Uses command line args to prevent headless Chrome hanging: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2885
Also adds in the `show_me_the_cookies` gem, to allow for a browser-agnostic way of accessing the cookies.
=> Chrome and cookies

.rubocop.yml
Please merge if you're happy with the change.  I'm not sure what happens with the version number for changes to the rubcicop.yml as it is pulled directly from GitHub rather than via the gem.
=> Turned off the Rails/RefuteMethods cop

CHANGELOG.md, README.md, lib/minitest/rake_ci_plugin.rb, lib/ndr_dev_support/integration_testing.rb, lib/ndr_dev_support/integration_testing/flakey_tests.rb, ndr_dev_support.gemspec
Adds a `flakey_test` method to minitest's DSL. Positioning as a pragmatic necessary evil, given CI pipelines are being affected.
If a test declared as "flakey" fails, but then passes after retries, it will be reported as a Pass. However, the CI will additional report it as being flakey (in a purple bubble to Slack).
=> Flakey tests

CHANGELOG.md, lib/minitest/rake_ci_plugin.rb, lib/tasks/ci/redmine.rake
This PR adds the minitest seed used to the output sent to slack, to aid in local reproduction when things don't go to plan.
=> Seed reporting

CHANGELOG.md, lib/ndr_dev_support/integration_testing/drivers/switchable.rb, lib/ndr_dev_support/version.rb
ndr_dev_support v5.8.2 was released 2020-07, but the changes were only tagged, and never merged back to the master branch.
=> Merge v5.8.2 changes from 2020-07 to master

.travis.yml, CHANGELOG.md, ndr_dev_support.gemspec
With the [release of Ruby 3.0](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/), this PR adds test coverage to NDR's base gem for the new Ruby version.
=> # add Ruby 3.0 to the travis matrix

CHANGELOG.md, config/rubocop/ndr.yml, ndr_dev_support.gemspec
This PR relaxes the dependency on `rubocop` / `rubocop-rails`, in line with [our policy](https://github.com/publichealthengland/ndr_dev_support/blob/master/config/rubocop/ndr.yml#L1-L3) of sticking with the wider Ruby community's shared consensus by default.
Additionally, we add [`rubocop-rake`](https://github.com/rubocop-hq/rubocop-rake), which runs some basic sanity checks that are helpful given Rake's DSL doesn't always behave as might be expected. (These checks would've saved my bacon in the past!)
The driver here is that the version of Rubocop we're currently locked on blocks Ruby upgrade paths.
It may also be worth investigating the [`rubocop-minitest`](https://docs.rubocop.org/rubocop-minitest) extension as a separate PR.
=> Use up-to-date Rubocop

config/rubocop/ndr.yml
PR #83 introduced `rubocop-rake`, but didn't add it to the actual Rubocop base configuration that our projects inherit from.
This PR ensures that the new Cops get loaded.
=> Update NDR Rubocop config

.github/workflows/test.yml
This PR adds a new job that collates the result of the build matrix jobs; this means the repository's branch protection rules can target a single job.
=> # use utility action to collate matrix results

.github/CODEOWNERS
When we being to require code review, we primarily want to keep the process as open as possible.
However, one exception is the `version.rb` file, which is used during the release process (and changes to which might in future trigger a release automatically).
This PR, along with appropriate branch protection rules, ensures that changes to `version.rb` are signed off by an NDR admin.
=> # Add CODEOWNERS, with admins owning the version file

lib/ndr_dev_support/rubocop/executor.rb, lib/ndr_dev_support/rubocop/inject.rb, lib/ndr_dev_support/rubocop/range_finder.rb
The `parser` library quite rightly warns loudly when the exact version of Ruby it is expecting doesn't match the active Ruby (given a history of syntax validity changes even within tiny version bumps of Ruby).
However, these warnings are popping up in unexpected places, and are just noise - so get ignored.
Given that Rubocop itself now loads `parser/current`, ndr_dev_support (which is a dependency of all of our projects) triggers it too (by virtue of acting as a Rubocop plugin).
This PR preserves the warnings when they're relevant:
```
$ bundle exec rake rubocop:diff master
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri. …
```
=> # Suppress some parser/current warnings

.github/workflows/lint.yml
This PR adds a non-compulsory check to PRs, which runs `rubocop:diff` against the base branch.
The check will currently fail if no ruby changes are detected (as this PR is experiencing).
=> # Add new linting workflow for pull requests

README.md, lib/ndr_dev_support/integration_testing/flakey_tests.rb
Often, when investigating whether a test is flakey, it's helpful to be able to run a test multiple times. This tends to get done by either using a bash loop (which can be slow) or hacking about in the test file (which can get messy).
Using a bash loop to repeatedly instantiate a runner is slow:
```bash
for i in `seq 1 100`; do bin/rails test path/to/test.rb:123; done
```
And mucking around duplicating the test gets messy:
```diff
+ 100.times do |x|
- test 'something flakey' do
-   # ...
- end
+   test "something flakey - #{x}" do
+     # ...
+   end
+ end
```
This PR adds the `test_repeatedly` construct, to make the latter pattern (which executes more efficiently) quick and simple to do, whilst retaining some configurability.
```diff
- test 'something flakey' do
+ test_repeatedly …
```
=> Add 'test_repeatedly', for help with flakey tests

code_safety.yml, lib/tasks/audit_code.rake
This PR is a refactoring and feature enhancement of the `audit:code` code. It:
* refactors existing logic, to make it a little more reusable. (_the code still needs a major overhaul, ideally_)
* Makes interactive mode "lazy" - diffs are computed on the fly, making working with large, stale, repositories easier.
* Adds the ability for review information to be outputted as CSV, for external analysis / team allocation.
* Adds the ability for reviews to be filled using a CSV file, to allow a user to work on an isolated partition.
I've kept this as one big PR, rather than numerous smaller ones, as the end goal was to be able to partition large amount of code review and allocate it out in an out-of-band process, and all the changes here are needed for that.
One way of giving this a go is to …
=> Overhaul code review

.github/workflows/test.yml, gemfiles/Gemfile.rails52, gemfiles/Gemfile.rails61, ndr_dev_support.gemspec
This PR relaxes the gem dependency against `active_support`, and ensures we're testing against the in-support minor version series of Rails.
The next release of Rails is [due to be 7.x](https://twitter.com/bitsweat/status/1357897202299850752), but given it is evidently going to have breaking changes I've prevented `ndr_dev_support` from automatically working with it.
=> Allow usage / test against with Rails 6.1

CHANGELOG.md, lib/ndr_dev_support/integration_testing/flakey_tests.rb, ndr_dev_support.gemspec, test/integration_testing/flakey_tests_test.rb
[Minitest 5.11](https://github.com/seattlerb/minitest/blob/master/History.rdoc#label-5.11.0+-2F+2018-01-01) changed the return value of `Minitest::Test#run` to return a new intermediary `Result` object.
This PR ensures our `flakey_test` logic does the same, and raises the minitest dependency accordingly.
=> # Address issue with flakey_test / minitest 5.11+

CHANGELOG.md, lib/ndr_dev_support/rubocop/reporter.rb
A non-zero exit status means that downstream processes assume failure. In reality, we want to to fail only when there are lint issues.
This PR ensures that the exit status is zero unless linting issues are actually found. If a user has interactively run against a malformed range, they still receive a message to warn them that no changes were found to analyse.
=> Code linting: don't fail when there are no linkable changes

CHANGELOG.md, lib/ndr_dev_support/integration_testing.rb, lib/ndr_dev_support/integration_testing/drivers/chrome_headless.rb, ndr_dev_support.gemspec
Remove requirement for `webdrivers` gem. This should no longer be needed with recent `selenium-webdriver` versions, cf. https://github.com/titusfortner/webdrivers/issues/247
=> # Remove dependency on outdated webdrivers gem.

CHANGELOG.md, lib/ndr_dev_support/integration_testing.rb, lib/tasks/audit_bundle.rake
This fixes an issue when `minitest` 5.19.0 is used with `ndr_dev_support`, similar to https://github.com/freerange/mocha/issues/614
It also updates branch names used in `rake bundle:update gem=...` to start with `feature/`
=> Minitest fixes and updates to branch names

CHANGELOG.md, lib/tasks/audit_bundle.rake
This makes it easier to copy and paste the output from `rake bundle:update` into a terminal window.
=> Convenience updates for rake bundle:update

CHANGELOG.md, README.md, lib/ndr_dev_support/integration_testing.rb, lib/ndr_dev_support/integration_testing/drivers/chrome_headless_old.rb
This PR changes the default browser for integration tests to the new chrome headless browser. The old chrome headless driver can still be accessed as `:chrome_headless_old` cf. https://www.selenium.dev/blog/2023/headless-is-going-away/
=> Change default browser for integration tests to new headless Chrome

CHANGELOG.md, lib/ndr_dev_support/capistrano/ndr_model.rb
Reduce the default number of releases we keep on webapp servers to 3 (previously 5).
This does not change the number of releases we keep on daemon servers (default 5 unless overridden): we have much longer lived processes there, and I think there's more risk there of removing the filesystem under running code, e.g. when we have batch tasks that run for many hours and we do a number of beta redeployments on the same day.
This should help a little with our storage issues on various webapp servers.
=> Reduce the number of releases kept on application servers

CHANGELOG.md, lib/ndr_dev_support/capistrano/ndr_model.rb, lib/ndr_dev_support/capistrano/standalone_gems.rb
Capistrano: fix up installed gem permissions after deployment.
This fixes permissions in the `shared/bundle/` directory after deployment, to make it writeable by all deployers. We already set group permissions correctly in the `bundle` directory, but some gem installs ignore these permissions, so we need to fix them up. (I think they build files in `$TMPDIR`, and then move them across with the wrong group / user.) This is not immediately obvious as a problem, but sometimes makes it impossible for a single deployer to remove the installed gems for old ruby versions.
Capistrano: identify errors when installing out-of-bundle gems.
=> Capistrano: fix up installed gem permissions after deployment.

CHANGELOG.md, config/rubocop/ndr.yml
Allow either EnforcedShorthandSyntax Hash style
Tested locally by pointing another codebase at this branch and running `bin/rake rubocop:diff develop` with known code that triggered the `EnforcedShorthandSyntax` cop previously.
=> Allow either EnforcedShorthandSyntax Hash style

CHANGELOG.md, lib/ndr_dev_support/capistrano/assets.rb, lib/ndr_dev_support/capistrano/install_ruby.rb, lib/ndr_dev_support/capistrano/ndr_model.rb, ndr_dev_support.gemspec
This PR moves the `app:install_ruby` task currently in `era/config/deploy.rb` to `ndr_dev_support:install_ruby`, so all projects using `ndr_dev_support` get the same functionality: it will automatically install rbenv and the packaged ruby version using `/opt/rbenv.tar.gz`. (This is only useful for first-time ruby installation, not version updates.)
It also checks in `vendor/rbenv/` and can install `rbenv` and ruby versions from there (first-time installations and updates).
For usage, run `$ cap -e ndr_dev_support:install_ruby`:
```
------------------------------------------------------------
cap ndr_dev_support:install_ruby
------------------------------------------------------------
Ensure that the required ruby version is installed.
This can be installed from /opt/rbenv.tar.gz (first …
```
=> Install rbenv and ruby from /opt/rbenv.tar.gz or vendor/rbenv/

CHANGELOG.md, lib/ndr_dev_support/version.rb
This is a minor release, because it should continue to work for our CentOS and Amazon Linux 2023 deployments: I've tested it for the `era` and `api_upload_portal` repositories.
=> tag v7.3.0

CHANGELOG.md, lib/ndr_dev_support/capistrano/deploy_secrets.rb, lib/ndr_dev_support/capistrano/ndr_model.rb
This PR moves most of the `app:update_secrets` task currently in `era/config/deploy.rb` to `ndr_dev_support:deploy_secrets`, so all projects using `ndr_dev_support` get the same functionality.
It deploys secrets files added using the `add_secrets_repo` and `add_secrets` methods to the `shared` deployment directory.
For usage, run `$ cap -e ndr_dev_support:deploy_secrets`:
```
------------------------------------------------------------
cap ndr_dev_support:deploy_secrets
------------------------------------------------------------
Deploy updated application secrets to shared folders on application servers
To use this in a project, add something like the code below to your
Capistrano file config/deploy.rb, then run:
$ cap target app:update_secrets
namespace :app do
desc 'Update application …
```
=> Capistrano: deploy application secrets from a subversion or git repository

CHANGELOG.md, code_safety.yml, lib/ndr_dev_support/version.rb
This is a patch release: it adds support for deploying application secrets, but this is opt-in behaviour which does nothing unless explicitly triggered.
=> tag v7.3.1

CHANGELOG.md, gemfiles/Gemfile.rails61, gemfiles/Gemfile.rails70, lib/ndr_dev_support/capistrano/deploy_secrets.rb
This PR adds a missing ruby `require` for `ndr_dev_support:deploy_secrets`.
Workaround: without this, applications using this feature need to `require 'tmpdir'` in their `config/deploy.rb`.
We don't have a test harness for capistrano tasks, which is why this wasn't identified in testing. I've tested this by fixing the gem locally, and confirming that the extra `require` is no longer needed.
=> Add missing library required by ndr_dev_support:deploy_secrets

.github/workflows/test.yml, CHANGELOG.md, config/rubocop/ndr.yml, gemfiles/Gemfile.rails61, lib/ndr_dev_support/capistrano/ndr_model.rb, lib/ndr_dev_support/capistrano/preinstall.rb, lib/ndr_dev_support/capistrano/revision_logger.rb
Capistrano: add task deploy:preinstall to preinstall ruby and bundled gems
Capistrano: cap deploy:setup should be safe on existing deployments
Drop Rails 6.1 CI tests
=> Add task deploy:preinstall to preinstall ruby and bundled gems

CHANGELOG.md, code_safety.yml, lib/ndr_dev_support/version.rb
Patch release because this should not break any existing code. (Rails 6.1 is past end of life, and we don't use it anymore.)
Changes since v7.3.1:
* Capistrano: Add missing `tmpdir` requirement to deploy application secrets
* Capistrano: cap deploy:setup should be safe on existing deployments
* Capistrano: add task deploy:preinstall to preinstall ruby and bundled gems
* Drop support for Rails 6.1
=> tag v7.3.2

CHANGELOG.md, ndr_dev_support.gemspec
Update rubocop gem dependency to ~> 1.72 to support the use of `plugins` instead of `require`.
This is not a critical fix (i.e. we don't need to pull ndr_dev_support 7.3.2), just a convenience.
=> Update rubocop version dependency

.github/workflows/lint.yml, .github/workflows/test.yml, CHANGELOG.md, lib/ndr_dev_support/capistrano/install_ruby.rb, lib/ndr_dev_support/capistrano/ndr_model.rb
Deletes shared bundle files that no longer match any installed releases. For example, if the currently installed releases are all ruby 3.2 and 3.3., this will remove any installed ruby 3.1 gems.
For deployments with long-lived application servers, this limits the space growth of application deployments. There isn't anything yet to remove installed `.rbenv` versions: this is harder, because multiple deployments can share the same user account – possibly inside nested directories.
Capistrano: `deploy:preinstall` should fix up installed gem permissions. (Before this fix, `deploy:preinstall` would abort before fixing up gem permissions.)
Support Ruby 3.4.
=> Capistrano should cleanup bundled gems for old ruby versions
